[package]
name = "simpl-protocol-solana"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
base64 = "0.22.1"
bincode = "1.3.3"
solana-client = "2.1.7"
solana-sdk = "2.1.7"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
